/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeocodeRouteImport } from './routes/api.geocode'
import { Route as ApiRestaurantsRecrawlRouteImport } from './routes/api.restaurants-recrawl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantsRecrawlRoute = ApiRestaurantsRecrawlRouteImport.update({
  id: '/api/restaurants-recrawl',
  path: '/api/restaurants-recrawl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/restaurants-recrawl': typeof ApiRestaurantsRecrawlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/restaurants-recrawl': typeof ApiRestaurantsRecrawlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/restaurants-recrawl': typeof ApiRestaurantsRecrawlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/geocode' | '/api/restaurants-recrawl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/geocode' | '/api/restaurants-recrawl'
  id: '__root__' | '/' | '/api/geocode' | '/api/restaurants-recrawl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiRestaurantsRecrawlRoute: typeof ApiRestaurantsRecrawlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurants-recrawl': {
      id: '/api/restaurants-recrawl'
      path: '/api/restaurants-recrawl'
      fullPath: '/api/restaurants-recrawl'
      preLoaderRoute: typeof ApiRestaurantsRecrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiRestaurantsRecrawlRoute: ApiRestaurantsRecrawlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
