name: Trigger Crawler
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Request Crawler
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl https://schnitzellunch.se/.netlify/functions/restaurants-recrawl
